#! /bin/bash/

#Comando per entrare in bashrc
vi ~/.bashrc

#Dentro bashrc con export creamo una nuova variabile d'ambiente permanente
export PATH=$PATH:/usr/local/bin:/home/user/bin
export MY_VAR="my value"
