Vagrant.configure("2") do |config|
config.ssh.insert_key = false
config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ss    h/id_rsa']
config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.    ssh/authorized_keys"
# Define node1
  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/bionic64"
    node1.vm.network "private_network", ip: "192.168.30.10"
    node1.vm.provision "shell", path: "provision-node1.sh"
   end
 
# Define node2
  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/bionic64"
    node2.vm.network "private_network", ip: "192.168.30.20"
    node2.vm.provision "shell", path: "provision-node2.sh"
   end
end
